### ISSUE TITLE
Log file

### ISSUE THREAD

**Issue by klablabla** [valeriodelsarto/pogobot-helper#2]
Tried installing, but won't startup. 
Checked the token ID for telegram. Don't know what the issue is.
If there is an logfile I can see what is working and what not.

keep up the good work.

**Comment by valeriodelsarto** [comment]
Hi, I have to sort out why the log file is not created, I'll take a look at it as soon as possible. I just noticed that I forgot to mention that I created a specific virtualenv (https://virtualenv.pypa.io/en/stable/) for Python in my local installation, located in a subfolder named "env" (that is not uploaded into this repo). I'll add this to the README file as soon as possible. In the meanwhile, if you want to try it without a specific virtualenv, try to start the bot with the command

python3 pogohelper.py

and check what output you get. You can stop it whenever you want by pressing the CTRL+C combination.

**Comment by klablabla** [comment]
root@raspberrypi:/opt/pogobot-helper# python3 pogohelper.py
Traceback (most recent call last):
  File "pogohelper.py", line 2, in <module>
    from telegram import (ReplyKeyboardMarkup, ReplyKeyboardRemove, KeyboardButton, ParseMode, Bot)
ImportError: No module named 'telegram'

We tested te telegram key in python.

**Comment by valeriodelsarto** [comment]
Ok, please install the python telegram module with the command

pip install python-telegram-bot

then try it again! I'll update the documentation as soon as possible!

**Comment by klablabla** [comment]
pi@raspberrypi:~ $ sudo su
root@raspberrypi:/home/pi# cd /opt/
root@raspberrypi:/opt# pip install python-telegram-bot
Requirement already satisfied (use --upgrade to upgrade): python-telegram-bot in /usr/local/lib/python2.7/dist-packages/python_telegram_bot-7.0.1-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): future>=0.16.0 in /usr/local/lib/python2.7/dist-packages (from python-telegram-bot)
Requirement already satisfied (use --upgrade to upgrade): certifi in /usr/local/lib/python2.7/dist-packages (from python-telegram-bot)
Cleaning up...
root@raspberrypi:/opt# cd pogobot-helper
root@raspberrypi:/opt/pogobot-helper# python3 pogohelper.py
Traceback (most recent call last):
  File "pogohelper.py", line 2, in <module>
    from telegram import (ReplyKeyboardMarkup, ReplyKeyboardRemove, KeyboardButton, ParseMode, Bot)
ImportError: No module named 'telegram'

Allready installed. I also tested the bot key.

**Comment by valeriodelsarto** [comment]
Sorry, my fault, I suggested you to start it with Python3 (as I did) but then gave you the command that install dependencies into Python2 (pip)! Please try run

pip3 install python-telegram-bot

that will install dependencies into Python3 then try to start the bot again!

**Comment by klablabla** [comment]
root@raspberrypi:/opt/pogobot-helper# python3 pogohelper.py
2017-08-14 13:12:01,906 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other long poll or webhook (409)
2017-08-14 13:12:01,907 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other long poll or webhook (409)"
2017-08-14 13:12:04,464 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other long poll or webhook (409)
2017-08-14 13:12:04,465 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other long poll or webhook (409)"
2017-08-14 13:12:08,274 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other long poll or webhook (409)
2017-08-14 13:12:08,275 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other long poll or webhook (409)"
2017-08-14 13:12:13,961 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other long poll or webhook (409)
2017-08-14 13:12:13,963 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other long poll or webhook (409)"
2017-08-14 13:12:22,457 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other long poll or webhook (409)
2017-08-14 13:12:22,458 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other long poll or webhook (409)"
^C2017-08-14 13:12:35,183 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other long poll or webhook (409)


Now I have the following errors
Updated to the last change you made.

Tonight I have time to search again, I just was curious if it was working now.

**Comment by klablabla** [comment]
After reboot it's look like it is working a bit more:
I sent /start to the bot, this is the message I got in return:

root@raspberrypi:/opt/pogobot-helper# python3 pogohelper.py
2017-08-14 14:45:24,877 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/conversationhandler.py", line 296, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/commandhandler.py", line 172, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "pogohelper.py", line 191, in start
    update.message.reply_text(language["welcome2"])
UnboundLocalError: local variable 'language' referenced before assignment

**Comment by RvdHNL** [comment]
I see in the line the error is in the code says: 
`update.message.reply_text(language["welcome2"])`

Shouldn't that be `update.message.reply_text(languages["welcome2"])`

languages (plural)?

[edit]
or is it because it is not set yet, code sets translations for a lot of variables:
`
# Custom reply keyboards
def build_custom_keyboards(language):
    # Build custom keyboars with selected language
    global team_markup
    global confirm_markup
    global confirmok_markup
    global confirmyesno_markup
    global raid_markup
    global raidboss_markup
    global raidbossexpire_markup
    global sqlexpire
    global raid_friends_markup
    team_reply_keyboard = language["team_reply_keyboard"]
    team_markup = ReplyKeyboardMarkup(team_reply_keyboard, one_time_keyboard=True)
    
    confirm_reply_keyboard = language["confirm_reply_keyboard"]
    confirm_markup = ReplyKeyboardMarkup(confirm_reply_keyboard, one_time_keyboard=True)
    
    confirmok_reply_keyboard = language["confirmok_reply_keyboard"]
    confirmok_markup = ReplyKeyboardMarkup(confirmok_reply_keyboard, one_time_keyboard=True)
    
    confirmyesno_reply_keyboard = language["confirmyesno_reply_keyboard"]
    confirmyesno_markup = ReplyKeyboardMarkup(confirmyesno_reply_keyboard, one_time_keyboard=True)
    
    raid_reply_keyboard = language["raid_reply_keyboard"]
    raid_markup = ReplyKeyboardMarkup(raid_reply_keyboard, one_time_keyboard=True)
    
    raidboss_reply_keyboard = [KeyboardButton(s) for s in raidboss]
    raidboss_markup = ReplyKeyboardMarkup(build_menu(raidboss_reply_keyboard, n_cols=3))
    
    raidbossexpire = language["raidbossexpire"]
    raidbossexpire_reply_keyboard = language["raidbossexpire_reply_keyboard"]
    raidbossexpire_markup = ReplyKeyboardMarkup(raidbossexpire_reply_keyboard, one_time_keyboard=True)
    sqlexpire = ['+30 Minute','+45 Minute','+60 Minute','+75 Minute','+90 Minute','+105 Minute','+120 Minute']
    
    raid_friends_reply_keyboard = language["raid_friends_reply_keyboard"]
    raid_friends_markup = ReplyKeyboardMarkup(raid_friends_reply_keyboard, resize_keyboard=True, one_time_keyboard=True)

    return True
`

But not for welcome1 and welcome2

**Comment by klablabla** [comment]
Tried:
update.message.reply_text(language["welcome2"])

When I sent /start with telegram to the bot I get the following message:


root@raspberrypi:/opt/pogobot-helper# python3 pogohelper.py
2017-08-14 19:27:30,061 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/conversationhandler.py", line 296, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/commandhandler.py", line 172, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "pogohelper.py", line 191, in start
    update.message.reply_text(languages["welcome2"])
TypeError: list indices must be integers, not str

**Comment by valeriodelsarto** [comment]
Sorry @klablabla I was on holiday for a couple of days! The latest problem you found should be solved with my latest commit (a few minutes ago), please try it again and thanks for your patience 😄

**Comment by klablabla** [comment]
Thanks for the update, tried the new version but got the next error:


root@raspberrypi:/opt/pogobot-helper# python3 pogohelper.py
Traceback (most recent call last):
  File "pogohelper.py", line 1029, in <module>
    main()
  File "pogohelper.py", line 936, in main
    regex_raidfriends += language_menu["raid_friends_reply_keyboard"][0]+'|'
TypeError: can only concatenate list (not "str") to list

**Comment by valeriodelsarto** [comment]
You're absolutely right, yesterday I did some other localization updates (in order to add the multi-language support) and this caused another bug that I solved right now. Please update to the new version and let me know!

**Comment by klablabla** [comment]
I tried the update...

root@raspberrypi:/opt/pogobot-helper# python3 pogohelper.py
2017-08-17 08:13:07,197 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x76337af0>, 'Connect timed out. (connect timeout=5.0)')': /bot@@@HERE WAS MY TELEGRAM ID@@@/setWebhook
2017-08-17 08:13:12,320 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x76337af0>, 'Connect timed out. (connect timeout=5.0)')': /bot@@@HERE WAS MY TELEGRAM ID@@@/setWebhook
2017-08-17 08:13:13,543 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other long poll or webhook (409)
2017-08-17 08:13:13,544 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other long poll or webhook (409)"
2017-08-17 08:13:16,119 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other long poll or webhook (409)
2017-08-17 08:13:16,121 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other long poll or webhook (409)"

**Comment by valeriodelsarto** [comment]
Hi @klablabla , I suppose this will happen if you run two instances of this bot at the same time. Please make sure that there is no other "python3 pogohelper.py" already running (maybe check with ps and kill any other instances if present) then try it again!

**Comment by klablabla** [comment]
I was to happy it was going to work. didn't check it my fault.

Tried it again and got:

root@raspberrypi:/opt/pogobot-helper# python3 pogohelper.py
2017-08-17 11:06:05,783 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/conversationhandler.py", line 296, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/commandhandler.py", line 172, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "pogohelper.py", line 172, in start
    default_language = int(row[1])
UnboundLocalError: local variable 'row' referenced before assignment

**Comment by valeriodelsarto** [comment]
Another bug that should be solved, these localization updates are creating some pain 😄

**Comment by RvdHNL** [comment]
Can't make an omelet without breaking some eggs...

**Comment by klablabla** [comment]
And an other.

root@raspberrypi:/opt/pogobot-helper# python3 pogohelper.py
  File "pogohelper.py", line 215
    "%s"
       ^
SyntaxError: invalid syntax

**Comment by valeriodelsarto** [comment]
😄 should be solved now!

**Comment by klablabla** [comment]
Sorry.


root@raspberrypi:/opt/pogobot-helper# python3 pogohelper.py
2017-08-17 11:40:00,833 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/conversationhandler.py", line 296, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/commandhandler.py", line 172, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "pogohelper.py", line 174, in start
    with open('languages/'+str(languages[languages_id.index(default_language)]).lower()+'.json') as language_file:
UnboundLocalError: local variable 'default_language' referenced before assignment

**Comment by valeriodelsarto** [comment]
I forgot that, updated again!

**Comment by klablabla** [comment]
Now I get an message from the bot. I did set the language to English. But the respons was Italian.
I though I know he is asking for my ingame user name. When I sent that back I have to following message:

2017-08-17 17:37:57,733 - telegram.ext.dispatcher - ERROR - An uncaught error wa                                                       s raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/dispatcher.py", line                                                        270, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/conversationhandler.                                                       py", line 296, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/messagehandler.py",                                                        line 171, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "pogohelper.py", line 209, in received_information
    if not (text == language["confirmok_reply_keyboard"][0][0] and category == "                                                       gym"):
UnboundLocalError: local variable 'language' referenced before assignment

**Comment by valeriodelsarto** [comment]
Ok now the default language should be english and no more italian and the user can choose a different language when he register his profile. Also the latest bug should be solved, I added also some new records into the SQL script, please run also the command

sqlite3 pogohelper.db < pogohelper.db.sql

after the new git pull, then try to start the bot again!

**Comment by valeriodelsarto** [comment]
please try it again with latest updates, now log file should be generated into the log subdirectory!
