### ISSUE TITLE
After selecting an Raid no response.

### ISSUE THREAD

**Issue by klablabla** [valeriodelsarto/pogobot-helper#5]
The bot is working great now.
I can create an profile, new raid's.
But when I select an raid I don't get an respons from the bot. 
/r still works.

How can we organise the raid now? When you select the raid we should be able to say I'll be joinen in 15min. I'll take two more with me.

**Comment by valeriodelsarto** [comment]
Please check the content of file log/pogohelper.log.
Do you find any useful logs here?

**Comment by klablabla** [comment]
root@raspberrypi:/opt/pogobot-helper/log# vi pogohelper.log
o017-08-18 15:03:14,913 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
t@raspberrypi:/opt/pogobot-helper/log# vi pogohelper.log
2017-08-18 15:03:14,913 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/conversationhandler.py", line 296, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/regexhandler.py", line 172, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "pogohelper.py", line 746, in raidedit_management
    update.message.reply_text(language["raid_no_attendees"],
KeyError: 'raid_no_attendees'
2017-08-18 15:05:55,082 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/conversationhandler.py", line 296, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/regexhandler.py", line 172, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "pogohelper.py", line 746, in raidedit_management
    update.message.reply_text(language["raid_no_attendees"],
KeyError: 'raid_no_attendees'
2017-08-18 15:10:37,788 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/conversationhandler.py", line 296, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/regexhandler.py", line 172, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "pogohelper.py", line 746, in raidedit_management
    update.message.reply_text(language["raid_no_attendees"],
KeyError: 'raid_no_attendees'
2017-08-18 15:16:02,590 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/conversationhandler.py", line 296, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/regexhandler.py", line 172, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "pogohelper.py", line 746, in raidedit_management
    update.message.reply_text(language["raid_no_attendees"],
KeyError: 'raid_no_attendees'

**Comment by valeriodelsarto** [comment]
Probably I understood and solved this issue, please try it again with the latest version and let me know!

**Comment by valeriodelsarto** [comment]
I'm going to close this issue, let me know if the problem persist!
